### ISSUE TITLE
Firebase Support

### ISSUE THREAD

**Issue by PhearZero** [quasarframework/quasar-cli#200]
# Firebase Support
Adding Firebase support via modes. Creates src-firebase folder with the default template found in templates/firebase. 

### Runtime Workflow:
```
quasar mode -a firebase 

// Is Equal To

cp 'template' 'src-firebase'
firebase login --interactive && firebase init
```
If the user exits during the **init** command it will use the **default** template. 

### Running the build
```
quasar build -m firebase

// Is Equal To

cp 'dist' 'src-firebase/public' 
```
This is going to be a WIP to flush out the rest of the documentation. 

## Todo:
- [X] **SPA:** Build Single Page App for Firebase Hosting
- [ ] **PWA:** Build Progressive Web App for Firebase Hosting
- [ ] **SSR:** Build Server Side Rendering for Firebase Functions
